name: HMRC on GitHub

defaults:
  -
    scope:
      paht: ""
    values:
      layout: default
sass:
    sass_dir: _scss

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

category-list: 
    - Development Documentation
